import localFont from "next/font/local";
import "./globals.css";

import { DM_Sans } from '@next/font/google';

const dmSans = DM_Sans({
  weight: ['400', '500', '600' , '700', '800'], // Specify font weights as per your need
  subsets: ['latin'], // Choose the subsets required
  display: 'swap', // Optional: this can prevent layout shift
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    {/* ${geistSans.variable} ${geistMono.variable} */}
      <body
        className={` ${dmSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
